#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "sydar WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-keygen ./build/docs/sydar-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "sydar WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-rpc ./build/docs/sydar-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "sydar WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-core ./build/docs/sydar-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "sydar WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar ./build/docs/sydar.ts
else
    echo "building keygen"
    typedoc --name "sydar WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-keygen ./build/docs/sydar-keygen.ts
    echo "building rpc"
    typedoc --name "sydar WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-rpc ./build/docs/sydar-rpc.ts
    echo "building core"
    typedoc --name "sydar WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar-core ./build/docs/sydar-core.ts
    echo "building full"
    typedoc --name "sydar WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sydar ./build/docs/sydar.ts

fi